src/keypair.rs
src/settings.rs

This makes the binary file format compatible with the libp2p_crypto library

Fix binary key read/write logic

---

Cargo.lock
src/router/mod.rs
src/service/gateway.rs
src/service/mod.rs

While not used yet this will set the stage for the state channel work for packet transfer earnings (state channel)

Use new gateway service proto

---

.github/workflows/ci.yml
Cargo.lock
Cargo.toml
Makefile.toml
config/default.toml
config/metadata.deb.toml
package/raspi01/control/postinst
package/raspi01/control/preinst
package/raspi01/control/prerm
package/raspi01/control/service
package/raspi01/data/etc/helium_gateway/install_update
package/raspi01/data/etc/helium_gateway/settings.toml
package/raspi234/control/postinst
package/raspi234/control/preinst
package/raspi234/control/prerm
package/raspi234/control/service
package/raspi234/data/etc/helium_gateway/install_update
package/raspi234/data/etc/helium_gateway/settings.toml
src/cmd/update.rs
src/settings.rs
src/updater.rs

Adds raspi .deb support  

---

config/default.toml

Previous staging has become dev and a new server is used for staging.

Update staging definition

---

README.md

Signed-off-by: RitchieLi <ritchieli@risinghf.com>

[README.md] Fix klkgw target typo

---

Cargo.lock
Cargo.toml
src/cmd/add.rs
src/cmd/key.rs
src/cmd/mod.rs
src/curl.rs
src/lib.rs
src/main.rs
src/releases.rs
src/router/mod.rs
src/router/routing.rs
src/server.rs
src/service/api.rs
src/service/mod.rs
src/settings.rs

Add gateway transaction creation
* Upgrades crypto
* Introduces “add” command to generate an add_gateway transaction

Introduce add command

---

src/router/filter.rs

I believe this fixes the crash that occasionally happens in the xor filter
Fixes #50

Fix missing filter block

---

README.md

Mark raspi_64 tested (tested on pi 4 with RAK2287)

Mark raspi_64 tested

---

README.md

Add cache info to readme

---

README.md

Mark wisgate edge prime as tested

---

Dockerfile

Successfully tested by building docker image after making these changes.

remove rustfmt dep thanks to proto build improvement

---

src/region.rs
src/router/client.rs
src/router/dispatcher.rs

This PR makes Region copy, but shouldn't have any real impact on performance one way or the other.

impl Copy for Region

---

Cargo.lock
src/api/mod.rs
src/api/server.rs

Requires a merge and update of https://github.com/helium/proto/pull/114

Add local ecdh api support

---

src/gateway.rs
src/main.rs

Adds info logs to help debug seutp

---

src/router/client.rs
src/router/dispatcher.rs

Fixes region changes not getting dispatched to each of the router clients

Actuall dispatch region changes to router clients

---

.github/workflows/ci.yml

Small change to github workflow to add Tektelic packages to the build / release process.

Added tektelic package to CI builds

---

src/router/client.rs

minor typo on region message
Signed-off-by: Aaron Shaw <shawaj@gmail.com>

fix: minor typo on log message

---

README.md

adds a little extra info about ecc configuration defaults

fix: further clarify ecc defaults

---

package/mtcdt/control/prerm

Fix prerm script for mtcdt

---

.github/workflows/ci.yml
Makefile.toml
README.md
package/risinghf/control/postinst
package/risinghf/control/preinst
package/risinghf/control/prerm
package/risinghf/control/service
package/risinghf/data/etc/helium_gateway/install_update
package/risinghf/data/etc/helium_gateway/settings.toml

This is a pull request for the RisingHF RHF2S027 light hotspot. settings.toml already contains the settings for the ECC chip. Please review and comment on this PR. Thanks!

target: adding support for RisingHF RHF2S027 light hotspot

---

Cargo.lock
Cargo.toml
src/api/client.rs
src/api/mod.rs
src/api/server.rs
src/cmd/add.rs
src/error.rs
src/gateway.rs
src/packet.rs
src/router/client.rs
src/settings.rs
src/state_channel/channel.rs
src/traits/mod.rs
src/traits/txn_envelope.rs
src/traits/txn_fee.rs

Implements add_gateway_txn for the local api rpc and changes the cli to use it
Also some cleanup @madninja wanted to work in

Implement add_gateway_txn in the local rpc and convert cli to use it

---

src/updater/releases.rs

This allows for router and packaged targets for testnet

Add testnet channel

---

src/router/dispatcher.rs
src/settings.rs

Allow absent default routers

---

src/gateway.rs
src/router/client.rs
src/router/dispatcher.rs
src/router/store.rs

Revert "Initialize hold_time as early as possible"

---

.github/workflows/ci.yml
Cargo.lock
Cargo.toml
src/cmd/info.rs
src/region.rs
src/router/dispatcher.rs
src/service/gateway.rs
src/traits/msg_sign.rs

Looks up the default region params from settings.toml every time the main gateway  is swifched. Then swithc back as soon as the assserted parameters come back into play from the region_params stream

look up default region_params

---

src/gateway.rs
src/packet.rs

- Break apart the pull_resp constructors for the 2 rx_windows
- Change `DOWNLINK_TIMEOUT_SECS` into the form that it's always used.

Assume immediate downlink when timestamp is `0`

---

Cargo.lock
src/traits/base64.rs

bump deps, fix base64 changes

---

.github/workflows/ci.yml

Try to address GH deprecation warnings

Fix up CI dependencies

---

Cargo.lock
Cargo.toml
config/settings.toml
src/api/server.rs
src/beaconer.rs
src/cmd/server.rs
src/gateway.rs
src/main.rs
src/packet_router/mod.rs
src/region_watcher.rs
src/router/client.rs
src/router/dispatcher.rs
src/router/routing.rs
src/server.rs
src/settings.rs
src/sync.rs

* Switch slog to thr tracing crate
* Remove unused syslog support

Replace slog with tracing

---

Cargo.lock

Bump proto in Cargo.lock for price report support.

Update proto for price

---

Cargo.lock
Cargo.toml

This removes the ansi feature from tracing to save space

Remove ansi from tracing

---

.github/workflows/ci.yml

* Fix release artifacts missing for cross builds
* Clean up build name steps

Tidy up CI

---

Cargo.lock
src/api/mod.rs
src/api/server.rs
src/beaconer.rs
src/error.rs
src/gateway.rs
src/lib.rs
src/packet.rs
src/packet_router/mod.rs

* this also cleans up datarate handling to avoid string conversions 
* removes the local exposed sign function since external signers are not to exposed this way

Adds immediate time support for downlink packets

---

Cargo.lock
Cargo.toml

This increases buffer size so the max allowable UDP frame (~65k)

update semtech-udp to v0.10.7

---

README.md

fix: repair link and fix typo

---

Cargo.lock
src/api/client.rs
src/api/mod.rs
src/api/server.rs
src/cmd/info.rs
src/packet_router/mod.rs
src/server.rs
src/service/packet_router.rs

`helium_gateway info router` returns the router URI and whether the process is connected to the packet router

Add router as a new info key

---

Cargo.lock
Cargo.toml
src/settings.rs
src/traits/txn_fee.rs

And reduce binary size about 10% by removing clap color output

Remove light hotspots

---

src/cmd/info.rs

Info cache in the info command was not adding any value anymore
after the more expensive duplicate requests were all removed.
This removes the cache to save some space and complexity

Remove info cache

---

.github/workflows/ci.yml

fix: backout armv6/ armv7 builds

---

config/settings.toml

I think this should be true if you want to disable POC right?

Fix comment typo

---

Cargo.lock

This should help slower ecc implementations without affecting normal ones

bump ecc608 for increased recv retries

---

Cargo.lock
Cargo.toml
src/beaconer.rs

Beacon in a determinstic slot in the beacon interval

---

src/packet_router/mod.rs

Also removes from extraneous logging to reduce hpr log noise

Fix packet router reconnect on startup

---

README.md

Minor code block typo

---

src/beaconer.rs

This fixes the beacon tick causing endless beacons

Fix beacon tick sleep update
