README.md
Fixed build instructions in README to correctly state that cargo-make crate should be installed to build gateway-rs
=> replace make with cargo-make in build instructions

Cargo.lock, Cargo.toml, src/cmd/key.rs
This changes key info to be json output with an address and name key to make it easier to recognize the gateway on chain or in a console. 
Note that this _does_ add some overhead to the binary size of the service so we may want to make including the name in the output an optional crate feature at some point 
e.g. 
```
helium_gateway -c config key info
{
"address": "11NdhVHu8aszbZwyqCGiF759BJUG54eJE4MifunFpNKhXBbxjzD",
"name": "gentle-iron-elephant"
}
```
=> Add animal name to key info

package/dragino/data/etc/helium_gateway/settings.toml
The dragino platform name needs to be set to `dragino` in order for the release updater to find the release
=> Fix dragino platform name

config/default.toml
I wonder if we should people explicitly switch to prod router and default them to staging instead?
Generally, we have more leeway for updating Router on staging so if we want to keep the testing cycle of Router faster than what can be pushed to prod (every two to three weeks, I think), we should probably point the light hotspots to Staging for now?
=> Change default router to staging

README.md
I've added the region setting in the README file (somehow with my Dragino LPS8 I had to edit it manually, as I am in EU868 region), not sure if I listed all possible regions in my edit : 
`US915| EU868 | EU433 | CN470 | CN779 | AU915 | AS923 | KR920 | IN865`
I don't know if it is possible to "autodetect" the region from the platform settings directly, this might be useful :)
=> add region setting in README

Makefile.toml, config/conffiles
Add 'conffiles' control file to ipk package build and includes settings.toml in the conffiles. This address issue #40 where the settings.toml file is overwritten on upgrade.
This will apply to all ipk packages.
Tested on Dragino LPS8 and RAK 7258 (WisGate Edge Lite) to confirm upgrade from 1.0.0-alpha.6 upgrade to .8 did not overwrite settings.toml.
=> Add conffiles control file for ipk packages

package/dragino/control/prerm, package/klkgw/control/prerm, package/mtcdt/control/prerm, package/ramips_24kec/control/prerm
Stopping the service in prerm breaks the upgrade path. The postinst step will restart/reload the service which should pick up the newer version.
Fixes: #48
=> Do not stop the service in prerm

Cargo.lock, Cargo.toml, config/default.toml, src/cmd/add.rs, src/cmd/key.rs, src/keypair.rs, src/link_packet.rs, src/server.rs, src/settings.rs
This PR upgrades the crypto library
**NOTE** This creates a **NEW** key file called gateway_key.bin since the previously generated key.bin is an incorrectly generated ecc_compact key.
=> bump crypto, change default key

src/releases.rs
Fixes asset detection's reliance on .ipk as the package extension. This will allow deb files to be seen as releases too
=> Fix debian upgrade assset detection

Cargo.lock, Cargo.toml, src/gateway.rs, src/service/gateway.rs
Previously, every single UDP frame was printed at `info` level with the explanation "ignoring raw packet". Whether "ignoring" is good or bad isn't really clear to the user, so the new explanation is "GWMP frame received" and the log-level is bumped down to `debug`.
However, `PushData` frames are specially handled and continue to be printed at the `info` level. 
Whereas before they printed as so:
```
INFO ignoring raw packet PushData(Packet { random_token: 27289, gateway_mac: MacAddress { bytes: [0, 0, 0, 0, 4, 3, 2, 1] }, data: Data { rxpk: Some([V1(RxPkV1 { chan: 0, codr: _4_5, data: [0, 1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8, 109, 176, 243, 16, 109, 161], datr: DataRate(SF10, BW125), freq: 904.7, lsnr: 5.5, modu: LORA, rfch: 0, rssi: -112, rssis: None, size: 23, stat: OK, tmst: …
```
=> improve logs in gateway for received frames

README.md
- adds additional usage info about available commands and configuration settings (uses some info from https://docs.helium.com/mine-hnt/data-only-hotspots/)
- clarifies that region must be set at top of settings.toml (see #81 )
- marks raspi01 as tested
Relates-to: #81 
Signed-off-by: Aaron Shaw <shawaj@gmail.com>
Co-authored-by: Remko welling <pe1mew@gmail.com>
=> docs: add additional usage info

src/gateway.rs
I noticed issues when reconnecting a virtual device:
```
Aug 31 11:41:33.924 INFO rx1 downlink @7105435 us, 923.90 MHz, DataRate(SF10, BW500), len: 12 via MacAddress(01:02:03:04:05:06:08), module: gateway
Aug 31 11:41:38.925 WARN ignoring rx1 downlink error: SendTimeout, module: gateway
Aug 31 11:41:38.925 INFO mac existed, but IP updated: MacAddress(01:02:03:04:05:06:08), 127.0.0.1:48197, module: gateway
Aug 31 11:41:38.925 INFO received packet @3008 us, 904.50 MHz, DataRate(SF10, BW125), rssic: -112, snr: 5.5, len: 23 from MacAddress(01:02:03:04:05:06:08), module: gateway
Aug 31 11:41:40.566 INFO received packet @6104785 us, 904.10 MHz, DataRate(SF10, BW125), rssic: -112, snr: 5.5, len: 23 from MacAddress(01:02:03:04:05:06:08), module: gateway
```
The two `received packet` events in …
=> Spawn off downlinks

Cargo.lock, config/default.toml, src/gateway.rs, src/lib.rs, src/router/client.rs, src/router/store.rs, src/settings.rs, src/state_channel.rs
Store state channels in RAM, fix listen addrs
* Stores state channels in RAM
* Allows listen_addrs to be specified as hostnames for (e.g.) docker usage
Fixes #82
=> Simplify State Channel storage

config/default.toml, src/api/client.rs, src/api/mod.rs, src/api/server.rs, src/cmd/add.rs, src/cmd/info.rs, src/settings.rs
the existing hard-coded api listening address currently conflicts with other jsonrpc and grpc api servers (namely the one running in the traditional erlang miner software). making the api listener configurable allows it to be set via the toml settings config override or the environment variables strategy.
=> make api listening endpoint configurable

config/default.toml, src/api/client.rs, src/api/mod.rs, src/api/server.rs, src/cmd/add.rs, src/cmd/info.rs, src/settings.rs
Making the api endpoint the gateway listens on completely configurable raises security concerns by potentially exposing the endpoint on a different listening address then the localhost. By restricting the configurability to the listening port only this allows for running the gateway alongside other services that default to the same (4467) port as well as multiple gateways on the same host (typically for testing purposes).
=> convert configurable endpoint to port only

Cargo.toml
```
the cargo feature `strip` has been stabilized in the 1.58 release and is no longer necessary to be listed in the manifest
```
=> remove strip from manifest since stabilized

Cargo.lock, Cargo.toml, src/gateway.rs
`semtech-udp v0.8` has improvements to errors and uses the `macaddr` crate instead of the self-spun type.
=> update semtech-udp to 0.8

Cargo.lock, src/api/client.rs, src/api/mod.rs, src/api/server.rs, src/cmd/info.rs, src/keyed_uri.rs, src/keypair.rs, src/region.rs, src/router/dispatcher.rs, src/service/gateway.rs, src/settings.rs, src/traits/msg_sign.rs, src/traits/txn_fee.rs, src/updater/releases.rs
This sets the gateway to follow the asserted lorawan region by following the regions through the associated gateway-service. 
The helium-gateway cli adds a new `region` info argument which will fetch the currently set region for the gateway. 
**Note**
The region setting in `settings.toml` will be used as the initial setting until a region update is received from the chain. This means that if the hotspot is never location asserted on chain the region will remain set to the settings.toml value. 
The info region command will return the default setting if no chain setting is asserted or found
=> Adjust region based on blockchain

Cargo.lock, Cargo.toml, src/error.rs, src/router/dispatcher.rs, src/settings.rs
This adds regular gateway service (validator) block age checks to see if the validator is falling behind. If the service is more than 30 minutes behind a new gateway is selected. In order to avoid a thundering herd, the reconnect sits behind a backoff which exponentially backs of from 5seconds to 30 minutes between gateway selection.
=> Add validator backoff and block age checking

src/api/client.rs, src/error.rs, src/main.rs
#203 #202 are similar tickets where the user was not running `helium_gateway server` before trying to use the info command.
The cited error message is a little cryptic for a non-dev:
```
Error: Service(Service(tonic::transport::Error(Transport, hyper::Error(Connect, ConnectError("tcp connect error", Os { code: 146, kind: ConnectionRefused, message: "Connection refused" })))))
```
The changes in `main.rs` use the logger to output the error before shutting down, thus using the custom display in the error's attribute:
```
Feb 28 19:14:36.222 ERRO service error service transport error
```
Adding colons and debug to the lowest level error message yields somethiong similar to the original error message,  but a little nicer:
```
Feb 28 19:18:47.945 ERRO service error: service: …
```
=> Improve Error Msgs

rust-toolchain
We no longer need nightly features when compiling with rustc >= 1.59
=> Remove toolchain file

src/cmd/add.rs, src/error.rs, src/lib.rs, src/packet.rs, src/router/client.rs, src/service/gateway.rs, src/state_channel/channel.rs, src/state_channel/message.rs, src/state_channel/mod.rs, src/traits/base64.rs, src/traits/mod.rs
* Track sc_diff purchases returned by router in the router client.  This distinguishes between the first offer to request a full state channel and subsequent offers which only request a sc_diff. 
* Use a Base64 trait to capture base64url and base64 conversions.
=> Track state channel diffs 

Cargo.lock, config/default.toml, src/api/client.rs, src/api/server.rs, src/cmd/info.rs, src/cmd/key.rs, src/error.rs, src/keypair.rs, src/server.rs, src/settings.rs
This allows for an `onboarding` setting  in default.toml to specify the onboarding key location. For most hotspots this is _not_ required since the onboarding key is the same as the public key of the hotspot. This feature is primarily for some legacy hotspots that had a different onboarding key stored in an alternate ecc slot.
=> Allow for onboarding_key in config

Cargo.toml, src/keyed_uri.rs, src/keypair.rs, src/main.rs, src/region.rs, src/service/gateway.rs, src/settings.rs, src/traits/msg_sign.rs, src/updater/releases.rs
Some internal refactoring to use proper serde across more types. This also uses the `rc` feature of serve to add Arc<T> deserializer support
=> Use proper serde across more types

config/default.toml
supply the testnet default router config as part of the default.toml file since it's mutually exclusive to other default routers based on the release channel setting of the running hotspot. without these values the gateway process will immediately crash for missing `uri` and `pubkey` fields
=> adding a testnet router

config/default.toml
this is no longer needed, thanks to the addition of https://github.com/helium/gateway-rs/pull/240 so cleaning it up
=> remove now-optional testnet router

Cargo.lock, src/keyed_uri.rs, src/router/client.rs, src/router/dispatcher.rs, src/service/gateway.rs, src/service/mod.rs
This requires the staked validator pool to have more open grpc ports than they do today. Before merging and releasing this branch, ensure that the validator pool has agreed to do so.  May need some feature adds there to allow for grpc port gossip (i.e. don't use 8080)
=> Use the static list as seeds to find a validator

src/router/client.rs, src/router/dispatcher.rs, src/state_channel/channel.rs
This keeps router clients alive even if the service gateway changes to allow for packet routing to continue until new gateway is received or if no further progress can be made without a gateway.
Once a routing_client requires a gateway to continue all packets will error out until a gateway is associated.
Routing clients are stopped and removed when a routing update arrives that no longer has the target oui/keyey_uri as a pair in its list
=> Adjusts router client to stay alive

config/default.toml, src/keyed_uri.rs, src/router/dispatcher.rs, src/router/routing.rs, src/settings.rs, src/state_channel/channel.rs
This is a change to default.toml where we now just have one list of default routers to target when packets are not known to exisitng helium routers.
=> default routers to packet purchasers

src/gateway.rs, src/router/client.rs, src/router/dispatcher.rs, src/router/store.rs
Without shoving it into the radio layer, we want to know how long the packet is sitting in the system.
When a gateway is already connected, the hold_time is `0` and that doesn't really tell us anything.
=> Initialize hold_time as early as possible

src/gateway.rs, src/router/client.rs, src/router/dispatcher.rs, src/router/store.rs
Don't expose QeuPacket to the wide-world of sports.
Another option would be to roll received_time into the `Packet`. But
I'm not sure that those things are so closely related that we could
continue to call it `Packet`.
=> thread received time

src/updater/releases.rs
A recent nightly toolchain introduces some new lints. These new lints are blocking a couple PRs which need to rebase on top of this PR.
=> Fix nightly lints

config/default.toml
Note that the ingest_uri is not `https` because of lack of consistent/recent ssl certs and implementations on a number of embedded platforms. 
cc @jadeallenx
=> configure default mainnet poc ingest uri

src/beaconer.rs
Fixes the following failure to run the tests:
```
$ cargo test
Compiling gateway-rs v1.0.0-alpha.31 (gateway-rs.main)
error[E0599]: no function or associated item named `propietary` found for struct `PHYPayload` in the current scope
--> src/beaconer.rs:202:37
|
202 |     let phy_payload_a = PHYPayload::propietary(b"poc_beacon_data");
|                                     ^^^^^^^^^^
|                                     |
|                                     function or associated item not found in `PHYPayload`
|                                     help: there is an associated function with a similar name: `proprietary`
For more information about this error, try `rustc --explain E0599`.
error: could not compile `gateway-rs` due to previous error
```
=> Fix spelling

Cargo.toml, config/default.toml, src/beaconer.rs
Fixes some configuration values for the default endpoints the helium_gateway should call to in order to receive the remote entropy data as well as the default (mainnet) endpoint for submitting beacon reports to.
re-introduces the tonic client request interceptor from early testing to allow injecting an "auth" token into the post requests to the grpc beacon ingestor service.
since these requests will be over plaintext http2 and not https2 this token is intended more as a "fail fast if the beacon is not intended for the network in question and as a result is named "ingest token" instead of "auth token" (or similar) in the public-facing configuration and defaults to `mainnet`
=> fixing workspace dependencies; config values

lorawan/src/lib.rs
For some reason, the `DATA_MIN_LEN` was being applied to the proprietary frames, but it's meant for only for the LoRaWAN data frames.
=> tolerate any length for proprietary frames

Cargo.lock, beacon/src/beacon.rs, src/beaconer.rs, src/error.rs, src/gateway.rs, src/packet.rs
Returns tmst and tx_power/powe fields from transmitted beacons to the beaconer caller to update poc beacon reports with the actual values used in the transmission, as well as pulling the tmst value from poc witness packets into the associated witness reports. This should enable creation of second-order beacons
=> return tx power and tmst to poc reports

lorawan/src/error.rs, src/beaconer.rs, src/cmd/update.rs, src/error.rs, src/gateway.rs, src/keypair.rs, src/router/filter.rs, src/settings.rs
This PR closes off a long-standing TODO in the beacon module. The motivation is to reduce the possibility of a thundering herd situation where gateways all beacon at the same time. It shouldn't be possible generally, because the previous beacon timer was relative to start-up time, but this additional jitter reduces the risk.
Requested by @Vagabond
=> Add some jitter to beacon intervals

src/settings.rs
This changes the default beacon interval to every 6 hours (instead of every 8) for initial fleet wide hotspot based beaconing.
=> Change default beacon interval to 6 hours

src/beaconer.rs
This disable secondary beacon support since it's not used and can cause some echo chamber witness storms
=> Disable secondary beaons

config/settings.toml, src/region_watcher.rs, src/router.rs
Instead of waitint 30 minutes on a failure to (re)connect to the packet router, use an exponential backoff on errors.
=> Use a reconnect backoff to back of on errors

src/service/config.rs
This will be corrected as part of config oracle production launch
=> Temporarily disable config response signature check

.github/cross-docker/Dockerfile-cross-debian-11, .github/workflows/ci.yml, Makefile.toml, README.md
The need to have alternate configuration setups made a simple `cross` build setup non trivial. This PR adds `cargo-make` to allow profiles that are not a simple target triplet (like the debian tpm setup)
=> Add cargo make back

Cargo.lock, beacon/Cargo.toml, beacon/src/beacon.rs
* This fixes up the beacon data the way it was intended.. the entropy is used to seed an RNG which then generates a random bytes of the requested length
* Sets the required length to 51 to allow for the lora header
=> The seed isn’t enough to generate the data

src/beaconer.rs, src/error.rs
This updates the beaconer timing to beacon at a random time within 10% of the beacon interval the first time region params are retrieved.
This allows for earlier beacons after a restart without a thundering herd beacon storm on fleet upgrades
=> Beacon sooner after region params are fetched

.github/workflows/ci.yml
This PR adds a new CI build step which pushes docker images to two quay.io repos:
1. All builds go to [quay.io/team-helium/test-images](https://quay.io/repository/team-helium/test-images?tab=tags&tag=latest)
- helps with testing one-off or experimental builds without clogging up the miner image repo
3. Tag/release builds to go [quay.io/team-helium/miner](https://quay.io/repository/team-helium/miner?tab=tags&tag=latest)
=> Publish docker images to quay.io

.github/workflows/ci.yml
This PR changes the way [test-images](https://quay.io/repository/team-helium/test-images?tab=tags&tag=latest) are tagged based on whether the build was triggered by a pull request or not:
- PR: `gateway-PR<PR NUM>-<7 dig sha>`
- example: `gateway-PR365-f2bbef0`
- other: `gateway-<OUTPUT OF GIT DESCRIBE>`
- example: `gateway-v1.0.0-alpha.33-60-g58e4162`
=> Use HEAD sha, not post-merge sha

.github/workflows/ci.yml
I had removed the fetch-depth argument (unintuitively, 0 means full depth) in #365, forgetting that it's needed for git-describe to work. The reason is that git-describe needs to walk the commit history to know how many commits it's been since the last tag.
=> Deconstrain fetch to allow for git-describe

beacon/src/beacon.rs
The verify method checks for equality of two beacons while allowing a reported beacon to have lower conducted power than the inferred one from region_params
=> Add Beacon.verify

Dockerfile
I transferred @isergieienkov branch for #374 to this repo so we can test CI.
I was defeated in my attempt to cross-compile with TPM support. So now the build phase happens under QEMU when building for architectures that differ from the host (notice the removal of `--from $BUILDPLATORM`). The downside is that this can be really slow. Additionally, it requires nightly because QEMU OOMs when updating the cargo cache unless we use sparse-registry.
=> Enable TPM+ECC support in docker builds

Cargo.lock, Cargo.toml, src/main.rs
Removes the —daemon flag and feature from helium_gateway since it is no longer maintained and did not work well.
The use can be replaced by a proper use of an init like unlix process to control the fork behavior
=> Remove —daemon flag

README.md
Readme was broken due to code tags being in the wrong places
=> fix: code tags in wrong places

Cargo.lock
updates the version of helium-proto to allow cargo to resolve rand crate/trait dependency confusion between the one it defines and the one it pulls transitively via the beacon subcrate here
=> update proto for oracle compatibility

.github/workflows/ci.yml, Dockerfile
These manifests break some users' builds when using these images as base-images.
Closes #409
=> Do not package attestation manifests with docker images

config/settings.toml, src/api/client.rs, src/api/mod.rs, src/api/server.rs, src/cmd/add.rs, src/cmd/info.rs, src/settings.rs
This adds support for the local listen address to be either a port or a fully specified `ip:port` listen address. It is _RECOMMENDED_ to only use the port configuration (which defaults the ip to local host listening only) to avoid exposing local apis to the open internet.
=> Add support for port or complete api socketaddr

.github/workflows/ci.yml, Makefile.toml, README.md
- add ecc608 based x86_64 image (LongAP uses this configuration)
- add docker builds for armv6 and armv7 via qemu
- change the build and push step to use the prebuilt docker action
- add github actions cache to builder action step to speed up future builds
- fix typos and add a bit more detail to readme
~~- gateway-mfr-rs uses aarch64-unknown-linux-gnu instead of aarch64-unknown-linux-musl so this unifies the two~~
~~- adds missing armv7-unknown-linux-gnueabihf which is built in gateway-mfr-rs~~
=> feat: add builds and use prebuilt action

Dockerfile
Building with QEMU is extremely simple, but it comes at the cost of very long Aarch64 builds. Let's see if we can make building on the host architecture work while selectively enabling TPM on only x86.
This is PoC PR until marked as "ready for review", and expect a corresponding level of jank.
=> Attempt to build without QEMU

src/gateway.rs, src/message_cache.rs, src/packet.rs, src/packet_router/mod.rs
If a gateway is connected, attempt to send all waiting packets. Otherwise we store and move on, the reconnection logic will trigger sending the packets when it is successful.
I changed the reconnect logging verbiage to only be about the connection. It's a bit confusing to read the logs and immediately see that you're "reconnecting" when the gateway is connecting for the first time.
We only attempt to reconnect on `Err(err)`. 
`Ok(None)` means the stream was closed explicitly by the server.
=> Do not attempt to reconnect on every packet received

.github/workflows/ci.yml
this should fix the tag error in https://github.com/helium/gateway-rs/actions/runs/4695602550/jobs/8324943218
```
Error: buildx failed with: ERROR: invalid tag "quay.io/team-helium/miner:gateway-${GITHUB_REF#refs/*/}": invalid reference format
```
=> fix: tag ref incompatible with GH actions

Dockerfile
I mistakenly disabled ECC608 on amd64 docker builds in #420. This PR re-enables the feature.
=> Re-enable ECC608 on amd64

Cargo.lock, config/settings.toml, src/beaconer.rs, src/settings.rs
This allows poc activity to be disabled to avoid unneeded RF
traffic. Useful for dataonly hotspots.
Fixes #427
=> Add settings poc enable flag

Cargo.lock, Cargo.toml, lorawan/Cargo.toml, lorawan/src/lib.rs, src/beaconer.rs, src/packet.rs
This constructs a short next beacon time when there is a failure to construct, transmit or (finally) deliver a beacon report.
=> Short next beacon time on beacon error

Cargo.lock, Cargo.toml, lorawan/src/error.rs, lorawan/src/lib.rs, src/gateway.rs, src/packet.rs
This filters out packets received from the packet forwarder that are not valid lorawan packets
=> Filter out non parseable lorawan packets

src/beaconer.rs, src/service/poc.rs
This connects to the ingest service while the beacon or witness report is being constructed.
This allows the connection to be established as soon as possible while the potentially slower report construction (due to signing overhead) happens
=> connect to ingest while signing

lorawan/src/lib.rs
This adds a number of length checks while parsing packets
=> Add length checks during parsing

Cargo.lock, Cargo.toml, src/keypair.rs
Upgrades helium-crypto to >= 0.8 and sets it to use the default EccConfig which adds some timing optimizations for ECC (over i2c) based signing
=> Bump crypto, default EccConfig use

Cargo.lock, src/api/mod.rs, src/api/server.rs, src/gateway.rs, src/keypair.rs, src/packet.rs, src/packet_router/mod.rs, src/service/packet_router.rs
* Requires https://github.com/helium/proto/pull/359 to merge and local Cargo.toml updated
* Expects router to be upgraded to support session keys. 
NOTE: On a connect all pending uplink packets are sent but only after the session key is established to avoid a large rush of signatures before the session key ie active. Two other alternatives are to (1) add a delay before sending queued packets with whatever key is available (gateway or session) or (2) send all waiting packets and then deal with session key initialization when it arrives after that
=> Session key for packet_router

src/packet_router/mod.rs
This means hotspots will try more often earlier on as they back of which would get them to connect faster given the host rate protections in place
=> Increase the number of hpr connect backof steps

src/packet_router/mod.rs
This adjusts the reconnect to only consider a connection complete after a session key is initialized. 
Doing this allows normal backof retry behavior for hotspots that fail session init, instead of the "successfully connected" 30 minute reconnect timer.
Fixes #446
=> session key failure reconnect backoff

lorawan/src/lib.rs
ALso fixes join accept parsing validation size
=> Add FHDR length validation

src/lib.rs
rustc 1.70 can’t figure out which `base64` we’re referring to.
be more explicit about what we’re using from where
Fixes #463
=> Fix older rust resolver

Cargo.lock, src/api/mod.rs, src/beaconer.rs, src/error.rs, src/keyed_uri.rs, src/keypair.rs, src/lib.rs, src/packet.rs, src/packet_router/mod.rs, src/service/conduit.rs, src/service/config.rs, src/service/mod.rs, src/service/packet_router.rs, src/service/poc.rs
This uses the same model as packet router streams but for PoC report ingest.
=> PoC Ingest Streams

src/service/conduit.rs
A conduit is really only connected if it has a stream to the server _and_ the session keypair is established
=> conduit connected check fix

src/beaconer.rs, src/gateway.rs, src/region_watcher.rs, src/service/conduit.rs, src/service/packet_router.rs, src/service/poc.rs
* With the IoT verifier using "any one beacon in known 6 hour windows" this PR adjusts the gateway beaconer to beacon at a completely random time in the six hour window. This _may_ introduce a single invalid beacon on every hotspot/helium_gateway restart again. 
* Adds a `module` tag to the service conduit log output to distinguish beaconed from packet router
=> Windowed Beacons

src/beaconer.rs
This adjusts the beaceon time to select a beacon time in the full first window, and moves it to the next window if in the past
=> adjust first beacon offset

Cargo.lock, src/api/server.rs, src/base64.rs, src/beaconer.rs
=> update time crate, fix clippy
